/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTable;

/**
 *
 * @author Sayid
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelSiswa = new javax.swing.JTable();
        btnDeleteMentor = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelMentor = new javax.swing.JTable();
        btnDeleteSiswa = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TabelSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Siswa", "Email Siswa", "No.hp Siswa", "Kelas Siswa", "Password Siswa", "Alamat Siswa", "Kelamin Siswa", "Email Mentor"
            }
        ));
        TabelSiswa.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TabelSiswa);

        btnDeleteMentor.setText("Delete Mentor");

        btnLogout.setText("LogOut");

        TabelMentor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Mentor", "Email Mentor", "No.hp Mentor", "Alamat Mentor", "Lulusan Mentor", "Password Mentor", "Kelamin Mentor", "Jadwal Mentor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelMentor.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(TabelMentor);
        if (TabelMentor.getColumnModel().getColumnCount() > 0) {
            TabelMentor.getColumnModel().getColumn(0).setResizable(false);
            TabelMentor.getColumnModel().getColumn(1).setResizable(false);
            TabelMentor.getColumnModel().getColumn(2).setResizable(false);
            TabelMentor.getColumnModel().getColumn(3).setResizable(false);
            TabelMentor.getColumnModel().getColumn(4).setResizable(false);
            TabelMentor.getColumnModel().getColumn(5).setResizable(false);
            TabelMentor.getColumnModel().getColumn(6).setResizable(false);
            TabelMentor.getColumnModel().getColumn(7).setResizable(false);
        }

        btnDeleteSiswa.setText("Delete Siswa");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnLogout)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnDeleteSiswa)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeleteMentor))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 764, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteMentor)
                    .addComponent(btnLogout)
                    .addComponent(btnDeleteSiswa))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    public void addActionListener(ActionListener a) {
        btnDeleteMentor.addActionListener(a);
        btnLogout.addActionListener(a);
        btnDeleteSiswa.addActionListener(a);
    }
    
    public JButton getBtnDeleteMentor() {
        return btnDeleteMentor;
    }
    
    public JButton getBtnDeleteSiswa() {
        return btnDeleteSiswa;
    }
    
    public JButton getBtnLogout() {
        return btnLogout;
    }
    
    public JTable getTabelMentor() {
        return TabelMentor;
    }
    
    public JTable getTabelSiswa() {
        return TabelSiswa;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TabelMentor;
    private javax.swing.JTable TabelSiswa;
    private javax.swing.JButton btnDeleteMentor;
    private javax.swing.JButton btnDeleteSiswa;
    private javax.swing.JButton btnLogout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
